apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  restartPolicy: Never
  volumes:
  - name: empty
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: empty
      mountPath: /usr/share/nginx/html
  - name: html-editor
    image: busybox
    volumeMounts:
    - name: empty
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
    - while true; do date >> /html/index.html; sleep 1; done
