apiVersion: v1
kind: Pod
metadata:
  name: empty
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /data
      name: volume-empty
  volumes:
  - name: volume-empty
    emptyDir: {}
