apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 5Gi
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  #  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  hostPath:
    path: "/volume"
