apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc01
spec:
  accessModes:
  - ReadWriteOnce
  #  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  # storageClassName: slow
