apiVersion: v1
kind: Pod
metadata:
  name: pod_pvc01
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/var/www/html"
      name: pvc01
  volumes:
  - name: pvc01
    persistentVolumeClaim:
      claimName: pvc01
