apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-env
spec:
  containers:
  - name: secret
    image: busybox
    command: ["/bin/sh", "-c", "env"]
    envFrom:
    - secretRef:
        name: primeira-secret
  restartPolicy: Never
